#ifndef nau8822_map_reg_h__
#define nau8822_map_reg_h__

#include <avr/io.h>

#ifdef __cplusplus
extern "C" {
#endif

#define POWER_MANAGMENT_1	(1)
#define DCBUFEN		(8)
#define AUX1MXEN	(7)
#define AUX2MXEN	(6)
#define PLLEN		(5)
#define MICBIASEN	(4)
#define ABIASEN		(3)
#define IOBUFEN		(2)
#define REFIMP		(0)
#define REFIMP_OFF	(0)
#define REFIMP_80k	(1)
#define REFIMP_300k	(2)
#define REFIMP_3k	(3)

#define POWER_MANAGMENT_2	(2)
#define RHPEN		(8)
#define LHPEN		(7)
#define SLEEP		(6)
#define RBSTEN		(5)
#define LBSTEN		(4)
#define RPGAEN		(3)
#define LPGAEN		(2)
#define RADCEN		(1)
#define LADCEN		(0)

#define POWER_MANAGMENT_3 (3)
#define AUXOUT1EN	(8)
#define AUXOUT2EN	(7)
#define LSPKEN		(6)
#define RSPKEN		(5)
#define RMIXEN		(3)
#define LMIXEN		(2)
#define RDACEN		(1)
#define LDACEN		(0)

#define AUDIO_INTERFACE	(4)
#define BCLKP		(8)
#define LRP			(7)
#define WLEN		(5)
#define WLEN_32		(3)
#define WLEN_24		(2)
#define WLEN_20		(1)
#define WLEN_16		(0)
#define AIFMT		(3)
#define RIGHT_JUST	(0)
#define LEFT_JUST	(1)
#define I2S_STANDARD	(2)
#define PCMAB		(3)
#define DACPHS	(2)
#define ADCPHS	(1)
#define MONO	(0)

#define COMPANDING	(5)
#define CMB8		(5)
#define DACCM		(3)
#define COMPANDING_OFF	(0)
#define DAC_U_LAW_COMPANDING	(2)
#define DAC_A_LAW_COMPANDING	(3)
#define ADCCM	(1)
#define ADC_COMPANDING_OFF	(0)
#define ADC_U_LAW_COMPANDING	(2)
#define ADC_A_LAW_COMPANDING	(3)
#define ADDAP	(0)

#define CLOCK_CONTROL_1	(6)
#define CLKM		(8)
#define MCLKSEL		(5)
#define MCK_DIV_1	(0)
#define MCK_DIV_1_5	(1)
#define MCK_DIV_2	(2)
#define MCK_DIV_3	(3)
#define MCK_DIV_4	(4)
#define MCK_DIV_6	(5)
#define MCK_DIV_8	(6)
#define MCK_DIV_12	(7)
#define BCLKSEL		(2)
#define BCLK_DIV_1	(0)
#define BCLK_DIV_2	(1)
#define BCLK_DIV_4	(2)
#define BCLK_DIV_8	(3)
#define BCLK_DIV_16	(4)
#define BCLK_DIV_32	(5)
#define CLKIOEN		(0)

#define CLOCK_CONTROL_2 (7)
#define WSPIEN_4	(8)
#define SMPLR		(1)
#define FILTER_SAMPLE_RATE_48KHZ	(0)
#define FILTER_SAMPLE_RATE_32KHZ	(1)
#define FILTER_SAMPLE_RATE_24KHZ	(2)
#define FILTER_SAMPLE_RATE_16KHZ	(3)
#define FILTER_SAMPLE_RATE_8KHZ		(5)
#define SCLKEN		(0)

#define NAU_GPIO	(8)
#define GPIO1PLL	(4)
#define GPIOPLL_DIV_1	(0)
#define GPIOPLL_DIV_2	(1)
#define GPIOPLL_DIV_3	(2)
#define GPIOPLL_DIV_4	(3)
#define GPIO1PL		(3)
#define GPIO1SEL	(0)
#define GPIO1_INPUT	(0)
#define GPIO1_TEMP_OK	(2)
#define	GPIO1_DAC_AUTOMUTE_STATUS	(3)
#define GPIO1_OUT_PLL	(4)
#define GIPO1_PLL_LOCK_STATUS	(5)
#define GPIO1_SET_OUTPUT_HIGH	(6)
#define GPIO1_SET_OUTPUT_LOW	(7)

#define JACK_DETECT_1	(9)
#define JCKMIDEN	(7)
#define JACDEN		(6)
#define JCKDIO		(4)

#define DAC_CONTROL	(10)
#define SOFTMT		(6)
#define DACOS		(3)
#define AUTOMT		(2)
#define RDACPL		(1)
#define LDACPL		(0)

#define LEFT_DAC_VOLUME	(11)
#define LDACVU		(8)
#define LDACGAIN	(0)

#define RIGHT_DAC_VOLUME	(12)
#define RDACVU		(8)
#define RDACGAIN	(0)

#define JACK_DETECT_2	(13)
#define JCKDOEN1	(4)
#define JCKDOEN0	(0)


#define ADC_CONTROL	(14)
#define HPFEN		(8)
#define HPFAM		(7)
#define HPF			(4)
#define ADCOS		(3)
#define RADCPL		(1)
#define LADCPL		(0)


#define LEFT_ADC_VOLUME	(15)
#define LADCVU		(8)
#define LADCGAIN	(0)

#define RIGHT_ADC_VOLUME	(16)
#define RADCVU		(8)
#define RADCGAIN	(0)

#define EQ_1_LOW_CUTOFF	(18)
#define EQM			(8)
#define EQ1CF		(5)
#define EQ1GC		(0)

#define EQ_2_PEAK_1	(19)
#define EQ2BW		(8)
#define EQ2CF		(5)
#define EQ2GC		(0)

#define EQ_3_PEAK_2	(20)
#define EQ3BW		(8)
#define EQ3CF		(5)
#define EQ3GC		(0)

#define EQ_4_PEAK_3	(21)
#define EQ4BW		(8)
#define EQ4CF		(5)
#define EQ4GC		(0)

#define EQ5_HIGH_CUTOFF	(22)
#define EQ5CF		(5)
#define EQ5GC		(0)

#define DAC_LIMITER_1	(24)
#define DACLIMEN		(8)
#define DACLIMDCY		(4)
#define DACLIMATK		(0)

#define DAC_LIMITER_2	(25)
#define DACLIMTHL		(4)
#define DACLIMBST		(0)

#define NOTCH_FILTER_1	(27)
#define NFCU1		(8)
#define NFCEN		(7)
#define NFCA0H		(0)

#define NOTCH_FILTER_2	(28)
#define NFCU2		(8)
#define NFCA0L		(0)

#define NOTCH_FILTER_3	(29)
#define NFCU3		(8)
#define NFCA1H		(0)

#define NOTCH_FILTER_4	(30)
#define NFCU4		(8)
#define NFCA1L		(0)

#define ALC_CONTROL_1	(32)
#define ALCEN		(7)
#define ALCEN_DISABLE	(0)
#define ALCEN_RIGHT_EN	(1)
#define ALCEN_LEFT_EN	(2)
#define ALCEN_BOOTH_EN	(3)
#define ALCMXGAIN		(3)
#define ALCMNGAIN		(0)

#define ALC_CONTROL_2	(33)
#define ALCHT		(4)
#define ALCSL		(0)

#define ALC_CONTROL_3	(34)
#define ALCM		(8)
#define ALCDCY		(4)
#define ALCATK		(0)

#define NOISE_GATE	(35)
#define ALCNEN		(3)
#define ALCNTH		(0)

#define PLLN_N		(36)
#define PLLMCLK		(4)
#define PLLN		(0)

#define PLL_K_1	(37)
#define PLL_K_2	(38)
#define PLL_K_3	(39)

#define CONTROL_3D	(41)
#define	DEPTH_3D	(0)

#define RIGHT_SPEAKER_SUBMIXER	(43)
#define RMIXMUT		(5)
#define RSUBBYP		(4)
#define RAUXRSUBG	(1)
#define RAUXMUT	(0)

#define INPUT_CONTROL	(44)
#define MICBIASV	(7)
#define RLINRPGA	(6)
#define RMICNRPGA	(5)
#define RMICPRPGA	(4)
#define LLINLPGA	(2)
#define LMICNLPGA	(1)
#define LMICPLPGA	(0)

#define LEFT_INPUT_PGA_GAIN	(45)
#define LPGAU		(8)
#define LPGAZC		(7)
#define LPGAMT		(6)
#define LPGAGAIN	(0)

#define RIGHT_INPUT_PGA_GAIN (46)
#define RPGAU		(8)
#define RPGAZC		(7)
#define RPGAMT		(6)
#define RPGAGAIN	(0)

#define LEFT_ADC_BOOST	(47)
#define LPGABST		(8)
#define LPGABSTGAIN	(4)
#define LAUXBSTGAIN	(0)

#define RIGHT_ADC_BOOST	(48)
#define RPGABST		(8)
#define RPGABSTGAIN	(4)
#define RAUXBSTGAIN	(0)

#define OUTPUT_CONTROL	(49)
#define LDACRMX		(6)
#define RDACLMX		(5)
#define AUX1BST		(4)
#define AUX2BST		(3)
#define SPKBST		(2)
#define TSEN		(1)
#define AOUTIMP		(0)

#define LEFT_MIXER	(50)
#define LAUXMXGAIN	(6)
#define LAUXLMX		(5)
#define LBYPMXGAIN	(2)
#define LBYPLMX		(1)
#define LDACLMX		(0)

#define RIGHT_MIXER	(51)
#define RAUXMXGAIN	(6)
#define RAUXRMX		(5)
#define RBYPMXGAIN	(2)
#define RBYPRMX		(1)
#define RDACRMX		(0)

#define LHP_VOLUME	(52)
#define LHPVU		(8)
#define LHPZC		(7)
#define LHPMUTE		(6)
#define LHPGAIN		(0)

#define RHP_VOLUME	(53)
#define RHPVU		(8)
#define RHPZC		(7)
#define RHPMUTE		(6)
#define RHPGAIN		(0)

#define LSPKOUT_VOLUME	(54)
#define LSPKVU		(8)
#define LSPKZC		(7)
#define LSPKMUTE	(6)
#define LSPKGAIN	(0)

#define RSPKOUT_VOLUME	(55)
#define RSPKVU		(8)
#define RSPKZC		(7)
#define RSPKMUTE	(6)
#define RSPKGAIN	(0)

#define AUX2MIXER	(56)
#define AUXOUT2MT	(6)
#define AUX1MIX2	(3)
#define LADCAUX2	(2)
#define LMIXAUX2	(1)
#define LDACAUX2	(0)

#define AUX1MIXER (57)
#define AUXOUT1MT	(6)
#define AUX1HALF	(5)
#define LMIXAUX1	(4)
#define LDACAUX1	(3)
#define RADCAUX1	(2)
#define RMIXAUX1	(1)
#define RDACAUX1	(0)

#define POWER_MANAGMENT_4	(58)
#define LPDAC		(8)
#define LPIPBST		(7)
#define LPADC		(6)
#define LPSPKD		(5)
#define MICBIASM	(4)
#define REGVOLT		(2)
#define IBADJ		(0)

#define LEFT_TIME_SLOT	(59)

#define MISC		(60)
#define PCMTSEN		(8)
#define TRI			(7)
#define PCM8BIT		(6)
#define PUDEN		(5)
#define PUDPE		(4)
#define PUDPS		(3)
#define RTSLOT		(1)
#define LTSLOT		(0)

#define RIGHT_TIME_SLOT	(61)

#define DEVICE_REVISION_NUMBER	(62)
#define DEVICE_ID	(63)

#define DAC_DITHER		(65)
#define MOD_DITHER		(4)
#define ANALOG_DITHER	(0)

#define ALC_ENHANCEMENT_1	(70)
#define ALCTBLSEL	(8)
#define ALCPKSEL	(7)
#define ALCNGSEL	(6)
#define ALCGAINL	(0)

#define ALC_ENHANCEMENT_2	(71)
#define PKLIMENA	(8)
#define ALCGAINR	(0)

#define SAMPLING_192KHZ	(72)
#define ADCB_OVER	(4)
#define PLL49MOUT	(2)
#define DAC_OSR32x	(1)
#define ADC_OSR32x	(0)


#define MISC_CONTROLS	(73)
#define SPIENA_4W	(8)
#define FSERRVAL	(6)
#define FSERFLSH	(5)
#define FSERRENA	(4)
#define NOTCHDLY	(3)
#define DACINMUTE	(2)
#define PLLLOCKBP	(1)
#define DACOSR256	(0)

#define INPUT_TIE_OFF	(74)
#define MANINENA	(8)
#define MANRAUX		(7)
#define MANRLIN		(6)
#define MANRMICN	(5)
#define MANRMICP	(4)
#define MANLAUX		(3)
#define MANLLIN		(2)
#define MANLMICN	(1)
#define MANLMICP	(0)

#define POWER_REDUCTION	(75)
#define IBTHALFI	(8)
#define IBT500UP	(6)
#define IBT250DN	(5)
#define MANINBBP	(4)
#define MANINPAD	(3)
#define	MANVREFH	(2)
#define MANVREFM	(1)
#define MANVREFL	(0)

#define AGC_PP_READOUT	(76)
#define AGC_PP_DETECTOR	(77)

#define STATUS_READOUT	(78)
#define AMUTCTRL	(5)
#define HVDET		(4)
#define NSGATE		(3)
#define ANAMUTE		(2)
#define DIGMUTEL	(1)
#define DIGMUTER	(0)

#define OUTPUT_TIE_OFF	(79)
#define MANOUTEN	(8)
#define SHRTBUFH	(7)
#define SHRTBUFL	(6)
#define SHRTLSPK	(5)
#define SHRTRSPK	(4)
#define SHRTAUX1	(3)
#define SHRTAUX2	(2)
#define SHRTLHP		(1)
#define SHRTRHP		(0)

#define SPI1_REGISTER	(87)
#define SPI1_VAL	(0x0115)

#define SPI2_REGISTER	(108)
#define SPI2_VAL	(0x003B)

#define SPI3_REGISTER	(115)
#define SPI3_VAL		(0x0129)


#ifdef __cplusplus
}
#endif

#endif // nau8822_map_reg_h__
